[theme]
background = "#191A1C"
primary = "#F0A674"
secondary = "#282A2E"
title = "#C5C8C6"
playing = "ff8400"
playing_selected = "#DD9C58"
playing_bg = "#00000"
highlight = "#C5C8C6"
highlight_bg = "#282A2E"
error = "#FFE4E4"
error_bg = "#BE7575"
statusbar = "#C5C8C6"
statusbar_progress = "#282A2E"
statusbar_bg = "#191A1C"
cmdline = "#C5C8C6"
cmdline_bg = "#444444"
